import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-200">Page Header</header>
        {children}
        <footer className="bg-red-200">Page Footer</footer>
      </body>
    </html>
  );
}
